# Exp 3: KRONOS DINOv2 + ImmuVis Preprocessing
training_mode: "dinov2"

model_name: "vitb16"
out_dim: 65536
drop_path_rate: 0.3
patch_size: 8
num_register_tokens: 0
ffn_layer: "mlp"

panel_config: "configs/all_panels_config.yaml"
tokenizer_config: "configs/all_markers_tokenizer.yaml"
marker_metadata_csv: "configs/marker_metadata.csv"
file_extension: "npy"
num_workers: 8

global_crops_number: 2
global_crops_scale: [0.48, 1.0]
global_crops_size: [128, 128]
local_crops_number: 8
local_crops_scale: [0.16, 0.48]
local_crops_size: [64, 64]

device: "cuda"
epochs: 200
batch_size: 8
gradient_accumulation_steps: 128

lr: 0.004
final_lr: 1.0e-6
warmup_epochs: 10
weight_decay: 0.04
weight_decay_final: 0.4
clip_grad: 3.0

warmup_teacher_temp_epochs: 30
warmup_teacher_temp: 0.04
teacher_temp: 0.07
teacher_momentum: 0.992

from_checkpoint: null
checkpoints_dir: "checkpoints/exp3_dinov2_immuvis"
save_checkpoint_freq: 10

tags: ["exp3", "kronos", "dinov2", "immuvis"]
comet_project: "immu-vis"
comet_workspace: "kugi8412"
comet_api_key: "V6s4QJ97ca130GE8M4G4MlU5D"
