encoder:
    ma_layers_blocks: []
    ma_embedding_dims: []
    pm_layers_blocks: [1] 
    pm_embedding_dims: [768] 

    encoder_type:
      type: dino
      module_parameters:
        version: "v3"
        model_size: "base"
        freeze_backbone: false
        target_dim: 768

    hyperkernel:
      kernel_size: 1
      padding: 0
      stride: 1
      use_bias: true

decoder:
  decoded_embed_dim: 768
  num_blocks: 4
  scaling_factor: 16
  
  block_type:
    type: vit
    module_parameters:
       num_heads: 12

  hyperkernel:
      kernel_size: 1
      padding: 0
      stride: 1
      use_bias: true

# Data configuration
panel_config: configs/all_panels_config.yaml
tokenizer_config: configs/all_markers_tokenizer.yaml
input_image_size: [128, 128]
num_workers: 8
batch_size: 8
device: cuda
lr: 1.5e-4
final_lr: 8e-6
weight_decay: 0.05
gradient_accumulation_steps: 1
epochs: 200
frac_warmup_steps: 0.2
min_channels_frac: 0.75
spatial_masking_ratio: 0.6
fully_masked_channels_max_frac: 0.5
mask_patch_size: 16
from_checkpoint: null
checkpoints_dir: checkpoints
save_checkpoint_freq: 10
beta: 0.5

# Comet.ml logging
# Masking & activation
mask_strategy: learnable
output_activation: sigmoswish
activation_beta: 2.0
uncertainty_method: evidential
evidence_reg_coeff: 0.01

tags: ["dinov3", "hyperkernel", "200epochs"]
comet_project: "immu-vis"
comet_workspace: "kugi8412"
# comet_api_key: set COMET_API_KEY env var
